// Generated by CoffeeScript 1.10.0
(function() {
  var Resources, global;

  Resources = "data/HelloWorld.png";

  global = typeof exports !== "undefined" && exports !== null ? exports : this;

  global.Resources = Resources;

  global.lib = {};

  global.utils = {};

  global.components = {};

}).call(this);

//# sourceMappingURL=init.js.map
