// Generated by CoffeeScript 1.10.0
(function() {
  var Block,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Block = (function(superClass) {
    extend(Block, superClass);

    function Block(config) {
      var dynamic, h, node, ref, ref1, ref2, ref3, show_center_point, w;
      Block.__super__.constructor.apply(this, arguments);
      this.setTag("Block");
      config = config != null ? config : {};
      w = (ref = config.width) != null ? ref : 30;
      h = (ref1 = config.height) != null ? ref1 : 30;
      show_center_point = (ref2 = config.show_center_point) != null ? ref2 : false;
      dynamic = (ref3 = config.dynamic) != null ? ref3 : false;
      this._world = config.world;
      this._width = w;
      this._height = h;
      node = cc.DrawNode.create();
      node.drawPoly([cc.p(-w / 2, -h / 2), cc.p(-w / 2, h / 2), cc.p(w / 2, h / 2), cc.p(w / 2, -h / 2)], cc.color(255, 0, 0, 128), 0.5, cc.color(255, 0, 0, 255));
      if (show_center_point) {
        node.drawDot(cc.p(0, 0), 5, cc.color.RED);
      }
      this.setRenderer(node);
      if (this._world) {
        if (dynamic) {
          this._world.add(this);
        } else {
          this._world.addStatic(this);
        }
      }
    }

    Block.prototype.update = function(dt) {
      return Block.__super__.update.apply(this, arguments);
    };

    Block.prototype.getBBox = function() {
      var h, pos, w;
      pos = this.getPosition();
      w = this._width;
      h = this._height;
      return [pos.x - w / 2, pos.y - h / 2, w, h];
    };

    return Block;

  })(utils.EntityBase);

  (typeof exports !== "undefined" && exports !== null ? exports : this).Block = Block;

}).call(this);

//# sourceMappingURL=block.js.map
