// Generated by CoffeeScript 1.10.0
(function() {
  var CocosScene;

  CocosScene = cc.Scene.extend({
    onEnter: function() {
      var director, listener;
      this._super();
      director = cc.director;
      utils.SceneManager.enterScene("EntryScene");
      this.scheduleUpdate();
      listener = cc.EventListener.create({
        event: cc.EventListener.KEYBOARD
      });
      listener.onKeyPressed = function(keycode, event) {
        return utils.InputManager.onKeyPressed(keycode, event);
      };
      listener.onKeyReleased = function(keycode, event) {
        return utils.InputManager.onKeyReleased(keycode, event);
      };
      return cc.eventManager.addListener(listener, this);
    },
    update: function(dt) {
      this._super();
      utils.InputManager.update(dt);
      return utils.SceneManager.update(dt);
    }
  });

  utils.CocosScene = CocosScene;

}).call(this);

//# sourceMappingURL=cocos_scene.js.map
